/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.

By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-value*/

var a = 0;
var b = 1;
var result = a + b;
var total = 0

for ( var i = 0; result < 4000000000; i++) {
  if (result % 2 === 0 ) {
    total += result;
  }
  result = a + b;
  a = b;
  b = result;
};
console.log(total);
